# Generated by Django 3.2.4 on 2021-10-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorid', models.CharField(max_length=1000)),
                ('blogcategory', models.CharField(max_length=100)),
                ('btitle', models.TextField(max_length=90)),
                ('bdescription', models.TextField()),
                ('battachment', models.ImageField(default='', upload_to='static/documents/')),
                ('bthumbnail', models.ImageField(default='', upload_to='static/thumbnail/')),
                ('blogdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
                ('cimage', models.ImageField(default='', upload_to='static/category/')),
                ('ADD_DATE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=150)),
                ('working', models.CharField(max_length=80)),
                ('profile_picture', models.ImageField(default='', upload_to='static/profilepic/')),
            ],
        ),
    ]
